import React from 'react';

const MethodologyContent = () => {
  return (
    <div className="methodologyContainer">
      <div className="example-text-container">
        NOTE: this is a draft methodology
      </div>
      <p className="methodology-intro"> The Methodology was created by the <a href="https://snappartnership.net/groups/managing-soil-carbon/" target="_blank">SNAPP: Managing Soil Carbon Working Group</a>. Here's their overview:
      </p>
      <h5>What is soil health and why focus on organic matter? </h5>
      <p>Soil health is a concept that has emerged out of decades of work covering other related concepts, including soil fertility, soil quality, and soil health. All of these conceptualizations of what makes a “good” soil have struggled with how to reduce soils to measurable indicators. All approaches have come up with lists and most of those lists overlap in certain indicators. In the current approaches to soil health—as with the earliest work in soil science—there is broad acknowledgement of the physical, chemical, and biological aspects of soil as essential to a healthy soil.
      </p>
      <p>The reason for this focus on the physical, biological, and chemical is that these three fields comprise essential, but distinct, aspects of soil. The physical components of the soil—such as the amount and type of certain rock-derived minerals—create the habitat in which plants and other organisms thrive. The structure of the soil relates to the amount of air and water that are available, which are as important to soil organisms as they are to us. The biology—or the organisms that live in the soil—are the workers that keep the economy of the soil running. These organisms transform energy provided from the aboveground ecosystem into biomass belowground, that they use to carry out essential chemical processes. Without the biology of soil, very little of the chemical processes could occur. Chemical transformations are what allow plants to grow when forms of nutrients that plants can’t use are converted into forms they can. Hence, current conceptualizations of soil health require measuring indicators of the biological, physical, and chemical components.
      </p>
      <p>In the history of soils work, soil organic matter has been featured as a particularly central component of healthy soils. One of the main reasons for this is that organic matter is the nexus of the physical, chemical, and biological sub-components of soil. It is connected to the physical because it binds water and creates a porous physical structure in which plants can thrive. It is connected to the biological because it provides an essential energy source to all of the organisms belowground that cannot photosynthesize and derive energy on their own. And it is connected to the chemical because the breakdown of organic matter releases elements like nitrogen, phosphorus, and micronutrients that plants require for growth.
      </p>
      <p>Soil organic matter is also an essential indicator of healthy soils because it is something that we can increase—and decrease—based on how we manage land. There is broad consensus that, for row-crop agriculture, building soil organic matter would benefit soil health.
      </p>
      <h5>Our approach</h5>
      <p>To create a user-friendly score for healthy soil, this guide focuses on the soil organic matter level of a farm. Comparing organic matter levels across farms, however, is misleading because different soils have different innate capacities to store certain types of organic matter. Soils with high amounts of clay, for instance, generally have much higher levels of organic matter than soils that are sandy. This is because clay minerals can bind organic matter on their surfaces and can be assembled into aggregates that protect organic matter. Sand minerals, by contrast, have very little ability to store organic matter. This is part of the reason why extremely sandy soils—like at the coast—are not highly productive farmland.
      </p>
      <p>Because of these different capacities of different soils to hold carbon, a sandy soil with 2% soil organic matter would be rich in organic matter; by contrast, a clayey soil with the same amount of organic matter could be considered degraded. Thus, only scoring farms based on organic matter concentrations would penalize farms based on their address, which is misleading.
      </p>
      <h6>The basic score</h6>
      <p>To avoid this challenge, we adopt an approach where we compare the soil organic matter level reported by a farm to publicly available data for soil organic matter levels on soils of similar type. We then create a normalized soil health score where:
      </p>
      <p>Healthy Soil Score = Farm Soil Organic Matter / Reference Soil Organic Matter x 100</p>
      <p>To make the score intuitive, we restrict its range to be between 0 and 100. To do this, we give all soils with Farm Soil Organic Matter > Reference Soil Organic Matter values of 100. This, of course, restricts the range of values > 100, but it communicates the essential information that those soils have achieved at least the amount of organic matter, as defined by their soil type.
      </p>
      <p>It is possible for a soil to have a value of organic matter greater than its reference for two reasons. First, the reference values are only estimates and can be imprecise. As our scientific understanding advances, this reference score will improve in precision. Second, there are different types of organic matter. Much of organic matter in agricultural soils is bound onto soil minerals and into aggregates, as was described above. Current scientific understanding suggests that this mineral-associated organic matter is determined by the amount and type of minerals in a soil. As such, there is likely a certain maximum amount of organic matter that a soil could achieve (with ease). Particulate organic matter—or the partially broken-down plant material that is sometimes visible on-or-in a soil, does not interact with soil minerals and can therefore be built up and maintained above reference levels. For this reason—and because of some cutting-edge science suggesting that organic matter can actually attract more organic matter—it may be possible for soil organic matter levels to exceed reference levels. The science behind these processes is still new, and we will update this approach as our understanding improves.
      </p>
      <h6>Defining the Reference Soil Organic Matter</h6>
      <p>Determining what a given soil’s organic matter level could be is challenging. This is challenging because the publicly available soils data within the United States—and elsewhere in the world—is too coarse in resolution to determine reliably what a particular farm’s soil type is, without going to that farm and doing intensive sampling. Thus, we have to rely on best guesses of what a particular soil type likely is, based on sampling elsewhere and knowledge about certain features of a location, like topography, climate, and vegetation type. But even if we had perfect knowledge of what soil type was present, we still lack the knowledge necessary of how much organic matter could be achieved for a specific soil type, as discussed above. To tackle this problem, we adopt three separate approaches, described below. All of the code written to implement these approaches is publicly available at: https://github.com/swood-ecology/soilc-targets
      </p>
      <h7>SSURGO</h7>
      <p>The United States Department of Agriculture has developed a soil classification system that allows us to name specific soils using terms that range from general to very specific. This is much like the way that biological species are named by Kingdom, Phylum, Class, Order, Famiy, Genus, and Species. Soils are classified based on Order, Sub-order, Great group, Group, and Series.
      </p>
      <p>In this approach, we use a GPS location for each farm and pass that to the web-based USDA SSURGO data platform. For the GPS location, we pull information on the soil series present. Since we cannot know with certainty the exact soil series, we instead collect the most likely series for that particular location. For each soil series in the list, we collect from the same database the maximum soil carbon level contained at a depth of up to 25 cm for that soil series. Then we estimate soil organic matter from soil carbon based on a scalar conversion, where soil organic matter is 62% carbon. We then calculate a weighted average of the soil organic matter scores based on the likelihood of all of the soil series for that location.
      </p>
      <p>The advantage of this approach is that it is rooted in a strong, mechanistic hypothesis that soils that are similar—i.e. are of the same series—should have similar organic matter levels. The downside is that there are so many soil series that soil carbon levels are sparse for each series and in many cases there are not enough data to calculate a reliable score.
      </p>
      <p>The current beta version of our tool only publishes results from this approach. This can be found at: http://cosima.nceas.ucsb.edu/soilc-targets/
      </p>
      <h7>SoilGrids</h7>
      <p>Our second approach uses mapped soil carbon data provided by ISRIC. These soil carbon data are modeled for every location on the planet based on a set of hundreds of thousands of soil samples. In our approach, we use a GPS point for each farm and create a 100-m buffer zone around that point. We calculate the maximum soil carbon value for that buffer zone and convert it to percent soil organic matter. We then use that value as the Reference Soil Organic Matter level.
      </p>
      <p>The advantage of this approach is that it does not face data limitations because there is a modeled soil carbon level for every cell in the map we use to extract data from. The limitation of this approach is that the 100-m buffer around the GPS could contain soils from different series. Where the SSURGO approach is rooted in mechanism but data poor, this approach is data rich but lacks the same mechanistic interpretation.
      </p>
      <h7>Sanderman et al PNAS 2017 estimates</h7>
      <p>Finally, a recent paper published by a SNAPP working group member estimated the maximum soil carbon potential across the globe by estimating the amount of carbon that has been lost from every soil due to land use change. This effort is a robust contribution, but suffers from two shortcomings in our application. First, the scale of the estimation is a 10 km grid cell, which is very coarse. This means that everything within a 10 km distance gets the same value.
      </p>
      <p>Neither the SoilGrids or Sanderman et al approaches have been implemented yet.
      </p>
      <h5>Important caveats</h5>
      <p>There are several important caveats to our approach.</p>
      <p>1. There is very little quantification of the levels of yield and environmental processes associated with a specific soil organic matter level. So, although we know that soil organic matter is generally useful for soil health in agricultural lands, we are not able to reliably estimate how much yield would change if a particular farm achieved a particular level of soil organic matter. This is crucial because it makes it extremely what amount of soil organic matter is sufficient to have a healthy vs. unhealthy soil.
      </p>
      <p>2. More soil organic matter may not always be better. In some cases, soil organic matter has been shown to have a negative relationship with crop productivity. Although, on average, soil organic matter might be important to soil health, there could be highly diverging relationships between organic matter and soil health in specific places. It is important to take this into account. More soil organic matter might not lead to more soil health for every farm.
      </p>
      <p>3. The centrality of organic matter to soil health may not make sense outside the narrow scope of row-crop agriculture. Soil organic matter has for a long time been central to agronomy because it provides nutrients for plant growth, holds moisture, and creates a physical structure for optimal agronomic production. For other systems—like rangelands or forests—high levels of soil organic matter may not be desirable. In rangelands, the highest levels of plant diversity can be found on soils that are very low in nutrients and organic matter—in fact, increasing nutrients can lower diversity. In forests, high carbon can be found in soils that have low disturbance, which is known to contribute to biological diversity. It is unknown whether soil organic matter should be considered important to soil organic matter for systems other than row-crop agriculture.
      </p>
      <p>4. Changes over time are likely more informative than comparisons among farms. Although scientists largely agree on measures that contribute to soil health, it is very difficult to compare among farms. As said before, this is because soils vary simultaneously in many properties, making it difficult to assess the causal impact of one variable relative to another soil. It is much easier—and likely more fruitful—to assess how particular soils change over time with the adoption of certain management practices. Comparing a soil to itself through time is likely a better indicator of whether the soil is performing well than by comparing a soil to a neighbor soil that differs in many properties.
      </p>
      <p>5. There is need for robust regional targets. To determine what counts as a healthy soil there needs to be more work defining what levels of key soil properties are achievable for specific regions, and what levels are optimal to achieve agronomic and environmental objectives. Currently we lack these targets. In our approach, here we generate proxies for these targets, but they are not themselves robust targets. As that science advances we will build those targets into this approach.
      </p>
    </div>
  );
};

export default MethodologyContent;